# Generated by Django 4.2 on 2026-01-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solicitudFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('nombre_activo', models.TextField()),
                ('accion_requerrida', models.TextField()),
                ('criticidad', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'solicitudFalla',
            },
        ),
    ]
