# Generated by Django 4.2 on 2026-02-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudFalla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudfalla',
            name='sistema_afectado',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
