# Generated by Django 4.2 on 2026-02-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudFalla', '0002_solicitudfalla_sistema_afectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudfalla',
            name='estado',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
